FROM php:8.3-apache

# Install dependencies
RUN apt-get update && apt-get install -y \
    git unzip libzip-dev \
    libpng-dev libjpeg62-turbo-dev libfreetype6-dev \
    libpcre3-dev gcc make autoconf && \
    docker-php-ext-configure gd --with-freetype --with-jpeg && \
    docker-php-ext-install gd && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Clone dan build Phalcon dari source
RUN git clone --depth=1 https://github.com/phalcon/cphalcon.git /tmp/cphalcon && \
    cd /tmp/cphalcon/build && \
    ./install && \
    echo "extension=phalcon.so" > /usr/local/etc/php/conf.d/phalcon.ini && \
    rm -rf /tmp/cphalcon

# Enable mod_rewrite
RUN a2enmod rewrite

# Set ownership & permission
RUN chown -R www-data:www-data /var/www/html && chmod -R 775 /var/www/html

EXPOSE 80